[project]
name = "p0001-samples-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.3"
dependencies = ["mcp[cli]>=1.7.1", "numpy>=2.2.5", "PyJWT>=2.8.0"]
